Escape special symbols
StepicOrg/stepik-translation-microservice pull request #8
Opened 2017-08-15 15:02 UTC by misteraverin

2017-08-16 09:38 UTC, KirillMakarov requested changes

2017-08-16 09:38 UTC, KirillMakarov commented on translation/models/translation_services.py
> +# delete accidently happened commas. E.g. "Blue, Sky, Orage" -> "Blue SKy, Orange" -> ["Blue", "Sky,", "Orange"]
Please, fix typos in description of the method

2017-08-16 09:38 UTC, KirillMakarov commented on translation/models/translation_services.py
> +def delete_strange_semicolons(texts):
semicolons is `;`, but method deletes commas.

2017-08-16 09:38 UTC, KirillMakarov commented on translation/models/translation_services.py
> +# delete accidently happened commas. E.g. "Blue, Sky, Orage" -> "Blue SKy, Orange" -> ["Blue", "Sky,", "Orange"]
What is precondition for texts? is it string or array of strings?

2017-08-16 09:38 UTC, KirillMakarov commented on translation/models/translation_services.py
> +def escape_symbols(texts):
why just this symobols are escaped?  May be https://docs.python.org/3.4/library/re.html#re.escape is more suitable?

2017-08-16 09:38 UTC, KirillMakarov commented on translation/models/translation_services.py
> +def delete_strange_semicolons(texts):
Why comma after sky is not removed here?

2017-08-17 08:50 UTC, misteraverin commented on translation/models/translation_services.py
> +def escape_symbols(texts):
@KirillMakarov actually we don't want to escape, we want ecode and `re.escape` act like this
`& -> \\ &` which is useless

2017-08-17 09:04 UTC, merged